on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Test Plan
    steps:
      - name: Install
        uses: actions/checkout@v3
      - name: Test execution Admin Suite
        run: npm i && npm run test